name Build Project

on
  push
    branches
      - main
  pull_request
    branches
      - main

jobs
  build
    runs-on ubuntu-latest

    steps
      - name Checkout code
        uses actionscheckout@v2

      - name Set up CMake
        uses actionssetup-cmake@v1

      - name Build with CMake
        run 
          cmake .
          cmake --build .
